version: "3.7"

services:
  gateway:
    build:
      context: ./gateway

  frontend:
    build:
      context: ./frontend

  backend:
    build:
      # context: .
      context: "https://github.com/LafiaEMR/openmrs-core.git#dev2"
      dockerfile: Dockerfile
